slice_name: 次日留存率
viz_type: big_number_total
params: '{"datasource":"0__table","viz_type":"big_number_total","metric":"weighted_retention_rate","time_range":"No filter","adhoc_filters":[{"expressionType":"SIMPLE","subject":"day_number","operator":"==","comparator":1,"clause":"WHERE","sqlExpression":null}],"y_axis_format":".1%"}'
uuid: 11111111-1111-4111-8111-111111111309
dataset_uuid: 11111111-1111-4111-8111-111111111204
version: 1.0.0
